sudo: required
services:
  - docker

before_install:
  - docker build -t ashpinl/docker-react-basic -f Dockerfile.dev .

script:
  - docker run ashpinl/docker-react-basic npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-basic"
  env: "DockerReactBasic-env"
  bucket_name: "elasticbeanstalk-us-east-2-847364809949"
  bucket_path: "docker-react-basic"
  on:
    branch: master