sudo: required
services:
  - docker
  
before_install:
  - docker build -t ashptestrn.azurecr.io/docker-react-basic-2:latest -f Dockerfile.dev .

script:
  - docker run ashptestrn.azurecr.io/docker-react-basic-2:latest npm run test -- --coverage

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master